


<div id="footer" class="footer bg-dark" style="margin-top: 100px; height: 150px">
    <a href="index.php?lang=en">cz</a>
    <a href="index.php?lang=bs">sk</a>
    <p>Some other footer content here</p>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script src="JS/upload_js/vendor/jquery.ui.widget.js" type="text/javascript"></script>
<script src="JS/upload_js/jquery.iframe-transport.js" type="text/javascript"></script>
<script src="JS/upload_js/jquery.fileupload.js" type="text/javascript"></script>
<script src="JS/data_tables_js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
<script src="JS/data_tables_js/jquery.dataTables.min.js" type="text/javascript"></script>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->

<script src="JS/myScript.js"></script>
</body>



</html>