<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=a.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="NASSA E-shop">
    <meta name="author" content="Norbert Nazarej">
    <title><?php echo $view->pageTitle; ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="CSS/myStyle.css">
    <link rel="stylesheet" href="CSS/data_table_css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="CSS/data_table_css/jquery.dataTables.min.css">


</head>

<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="index.php">Domu</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="admin.php">Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="extraItems.php">Diely</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Kosik</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="register.php">Register</a>
        </li>
    </ul>
</nav>


