<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=a.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="NASSA E-shop">
    <meta name="author" content="Norbert Nazarej">
    <title><?php echo $view->pageTitle; ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="CSS/myStyle.css">
    <link rel="stylesheet" href="CSS/data_table_css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="CSS/data_table_css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">


</head>

<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="main.php">Domů</a>
        </li>
        <?php if ($_SESSION['name'] === 'admin') {?>
        <li class="nav-item">
            <a class="nav-link" href="admin.php">Admin</a>
        </li>
        <?php } ?>
        <li class="nav-item">
            <a class="nav-link" href="extraItems.php">Diely</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="test.php">Test</a>
        </li>
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" href="#">Kosik</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" href="login.php">Login</a>-->
<!--        </li>-->
        <?php if (isset($_SESSION['name'])) {?>
        <li class="nav-item" >
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                     <?php
                        echo 'Vítejte ' . $_SESSION['name'];
                     ?>


                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="manageAcc.php">Sprava uctu</a>
                    <a class="dropdown-item" href="#">Košík</a>
                    <a class="dropdown-item" href="#">Vase Objednavky</a>
                    <a class="dropdown-item" href="connTest.php">Test</a>
                    <a class="dropdown-item" href="logout.php">Log out</a>
                </div>
            </div>
        </li>
        <?php } ?>

    </ul>
</nav>


