<?php require('View/Template/header.phtml') ?>


    <div class="container" style="margin-top: 100px;">
<div id="filterSection">
        <p>some random text here</p>
    </div>

    <div class="row">
        <div id="item" class="col-sm-4">
            <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
            <div id="in" class="card" style="width:300px">
                <img class="card-img-top" src="Pics/pic1.jpg" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Titulka itemu</h4>
                    <p class="card-text">Nejaky popis itemu</p>
                    <a href="#" class="btn btn-primary">Info</a>
                </div>
            </div>
        </div>

        <div id="item" class="col-sm-4">
            <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
            <div id="in" class="card" style="width:300px">
                <img class="card-img-top" src="Pics/pic1.jpg" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Titulka itemu</h4>
                    <p class="card-text">Nejaky popis itemu</p>
                    <a href="#" class="btn btn-primary">Info</a>
                </div>
            </div>
        </div>

        <div id="item" class="col-sm-4">
            <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
            <div id="item" class="card" style="width:300px">
                <img class="card-img-top" src="Pics/pic1.jpg" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Titulka itemu</h4>
                    <p class="card-text">Nejaky popis itemu</p>
                    <a href="#" class="btn btn-primary">Info</a>
                </div>
            </div>
        </div>

        <div id="item" class="col-sm-4">
            <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
            <div id="in" class="card" style="width:300px">
                <img class="card-img-top" src="Pics/pic1.jpg" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Titulka itemu</h4>
                    <p class="card-text">Nejaky popis itemu</p>
                    <a href="#" class="btn btn-primary">Info</a>
                </div>
            </div>
        </div>

        <div id="item" class="col-sm-4">
            <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
            <div id="in" class="card" style="width:300px">
                <img class="card-img-top" src="Pics/pic1.jpg" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Titulka itemu</h4>
                    <p class="card-text">Nejaky popis itemu</p>
                    <a href="#" class="btn btn-primary">Info</a>
                </div>
            </div>
        </div>

    </div>





</div>  <!-- End of container div -->

<?php require('View/Template/footer.phtml') ?>