<?php //require('View/Template/header.phtml') ?>
    <!doctype html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=a.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="NASSA E-shop">
        <meta name="author" content="Norbert Nazarej">
        <title><?php echo $view->pageTitle; ?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="CSS/myStyle.css">
        <link rel="stylesheet" href="CSS/data_table_css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="CSS/data_table_css/jquery.dataTables.min.css">


    </head>

<body>

    <div class="container" style="margin-top: 100px; ">


    <div class="row align-items-center justify-content-center" style="margin-bottom: 500px">

        <div class="col-md-6 col-md-offset-3">

            <h1>VITAME VAS NA STRANKE NASSA</h1>
            <h1>PROSIM VAS O PRIHLASENIE</h1>
            <?php if (!empty($inputError)) {
                    foreach ($inputError as $err) {
                        echo "<p>" . $err . "</p>";
                    }
                } ?>


                <?php if (!empty($dataError)) {
                    foreach ($dataError as $errIn) {
                        echo "<p>" . $errIn . "</p>";
                    }
                }
                ?>



            <form method="post" action="index.php">
                <label>Vas Email: </label><br>
                <input class="form-control" id="email" name="email" type="email" placeholder="Vložte svou e-mailovou adresu"><br>
                <label>Vas password: </label><br>
                <div id="response"></div>
                <input class="form-control" id="password" name="password" type="password" placeholder="Zadejte heslo"><br>
                <input class="btn btn-primary" id="login" type="button" name="submit" value="Login">


            </form>



        </div>

    </div>







    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="JS/upload_js/vendor/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="JS/upload_js/jquery.iframe-transport.js" type="text/javascript"></script>
    <script src="JS/upload_js/jquery.fileupload.js" type="text/javascript"></script>
    <script src="JS/data_tables_js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <script src="JS/data_tables_js/jquery.dataTables.min.js" type="text/javascript"></script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->

    <script src="JS/myScript.js"></script>
</body>



</html>

<?php //require('View/Template/footer.phtml') ?>