<?php require('View/Template/header.phtml') ?>

<div class="container" style="margin-top: 100px; ">

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" width="100px">Photo</th>
            <th scope="col" width="180px">Nazev Produktu</th>
            <th scope="col" width="170px">Farba</th>
            <th scope="col" width="180px">Velikost</th>
            <th scope="col" width="100px">Dostupnost</th>
            <th scope="col" width="130px">Vpis kvantitu</th>
            <th scope="col">Možnosti</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row"><a href="Pics/pic1.jpg"><img src="Pics/pic1.jpg" width="50px" height="30px"></a></th>
            <td>SHOT</td>
            <form>
            <td><div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte barvu</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div></td>
            <td><div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte velikost</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div></td>
            </form>
            <td>@mdo</td>
            <td><input maxlength="3" style="width: 35px"></td>
            <td><button type="button" class="btn btn-success">Pridat</button><button type="button" class="btn btn-danger" style="margin-left: 30px">Vymazat</button></td>
        </tr>
        <tr>
            <th scope="row"><img src="Pics/pic1.jpg" width="50px" height="30px"></th>
            <td>WIRE Carbon Vernice</td>
            <td><div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte barvu</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div></td>
            <td><div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte velikost</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div></td>
            <td>@mdo</td>
            <td><input maxlength="3" style="width: 35px"></td>
            <td><button type="button" class="btn btn-success">Pridat</button><button type="button" class="btn btn-danger" style="margin-left: 30px">Vymazat</button></td>
        </tr>
        <tr>
            <th scope="row"><img src="Pics/pic1.jpg" width="50px" height="30px"></th>
            <td>ERGO 4 CC</td>
            <td><div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte barvu</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div></td>
            <td>
                <div class="form-group">
                    <select class="custom-select" required>
                        <option value="">vyberte velikost</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <div class="invalid-feedback">Example invalid custom select feedback</div>
                </div>
            </td>
            <td>@mdo</td>
            <td><input maxlength="3" style="width: 35px"></td>
            <td><button type="button" class="btn btn-success">Pridat</button><button type="button" class="btn btn-danger" style="margin-left: 30px">Vymazat</button></td>
        </tr>
        </tbody>
    </table>








</div>  <!-- End of container div -->



<?php require('View/Template/footer.phtml') ?>