<?php require('View/Template/header.phtml') ?>

    <div class="container" style="margin-top: 100px; ">

<!--        <div id="sideBasket">-->
<!--        <center><h1>Shrnutí objednávky</h1></center>-->
<!--        <hr>-->
<!---->
<!--        </div>-->

        <div  id="baskIcon" >
            <button id="qtyIcon" class="btn btn-lg"><span><i class="fas fa-shopping-cart"></i>  <?php if(isset($_SESSION["basketItems"])){
                        echo count($_SESSION["basketItems"]);
                    }else{
                        echo 0;
                    }
                    ?></span></button>
<!--            <button id="qtyIcon" class="btn btn-lg"><span><i class="fas fa-shopping-cart"></i> </span></button>-->
<!--            <a href="#" style="text-decoration: none;">-->
<!--            <center><img src="Pics/basket.png" width="30px" height="20px" style="margin-top: 10px"></center>-->
<!--            <center><p id="selectedQP" style="margin-top: 5px;">--><?php
//                    if(isset($_SESSION["basketItems"])){
//                        echo count($_SESSION["basketItems"]);
//                    }else{
//                        echo 0;
//                    }
//                    ?><!--</p></center>-->
<!--            </a>-->
        </div>

        <div class="arrow_box" id="itemsInBasket" style="display:none;">
            <h1 style="margin-left: 20px">Vas Kosik</h1>
            <hr>
            <?php if(isset($_SESSION["basketItems"])){ ?>
            <?php
                $total = 0;
                foreach ($_SESSION["basketItems"]  as $key => $item) {
                    $total += intval($item['qty']) * intval($item['itemB']->getItemPrice()) ?>
<!--                <p>Name: --><?php //echo var_dump($item['itemB'])?><!--</p>-->
                <div  id="basketRmv" class="item_<?php echo $item['itemB']->getItemID() ?>">Name: <?php echo $item['itemB']->getItemName() ?> QTY: <?php echo $item['qty']?> <button id="deleteBask" class="btn btn-danger btn-sm" onclick="deleteItemFromBasket(<?php echo $item['itemB']->getItemID() ?>)"><input type="hidden" value="<?php echo $item['itemB']->getItemID() ?>"><span><i class="far fa-trash-alt"></i></span></button></div>
                    <hr>


                <?php }?>
            <?php } ?>
            <hr>
            <p>Total: <?php echo $total ?></p>
        </div>

        <!-- Modal -->
        <div id="itemSummaryModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">

                        <h4 class="modal-title">Přidat položku do košíku</h4>
<!--                        <h3>--><?php //echo $view->itemID; ?><!--</h3>-->
                    </div>
                    <div class="modal-body">

                        <div class="card mb-3">
                            <img id="cardImg" class="card-img-top" src="#" alt="">
                            <div class="card-body">

                                <h5 style="margin: 0" id="cardTitle" class="card-title"><b></b></h5>
                                <hr>
                                <p style="margin: 0" id="cardItemSize"> </p>
                                <p style="margin: 0" id="cardItemColor"> </p>
                                <p style="margin: 0" id="cardItemPrice"> </p>
                                <p style="margin: 0" id="cardItemQuantity"> </p>
                                <p> </p>
                            </div>
                        </div>

                        <form method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <center>
                                    <label for="product-name" class="col-form-label"><b>Zadejte množství:</b></label>
                                <input type="text" style="width: 60px" maxlength="3" class="form-control" id="enterQuantity">
                                </center>
                            </div>
                            <div class="form-group">
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button style=" margin-right: 50%" type="button" class="btn btn-danger" data-dismiss="modal">Zatvorit</button>
                        <input type="hidden" id="hiddenInputBasket" value="0">
                        <input  type="button" id="itemToBasketB" onclick="addItemToBasketClick()" value="Vložtit do košíku" class="btn btn-success">
                    </div>
                </div>

            </div>
        </div>
    </div>


    <!-- Modal -->

    <table class="table table-hover " id="itemTable">
        <thead>
        <tr>
            <th scope="col" width="100px">Photo</th>
            <th scope="col" width="180px">Nazev Produktu</th>
            <th scope="col" width="170px">Farba</th>
            <th scope="col" width="180px">Velikost</th>
            <th scope="col" width="130px">Dostupnost</th>
            <th scope="col">Možnosti</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($items as $item) { ?>
            <tr>
                <th scope="row"><a href="uploads/<?php echo $item->getItemImage()?>"><img src="uploads/<?php echo $item->getItemImage()?>" width="50px" height="30px"></a></th>
                <td id="indexItemName"><?php echo $item->getItemName()?></td>
                <td id="indexItemColor"><?php echo $item->getItemColor()?></td>
                <td id="indexItemSize"><?php echo $item->getItemSize()?></td>
                <td id="indexItemQuantity"><?php echo $item->getItemQuantity()?></td>
                <input type="hidden" id="getRowIDIndex" value="<?php echo $item->getItemID()?>">
                <td><button type="button" id="toggleModalIndexB" data-toggle="modal" data-target="#itemSummaryModal" onclick="addItemToBasket('<?php echo $item->getItemID()?>')" class="btn btn-success">Pridat</button></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    </div>  <!-- End of container div -->



<?php require('View/Template/footer.phtml') ?>