<?php require('View/Template/header.phtml') ?>

    <div class="container" style="margin-top: 100px; ">
    <div id="userConf" class="form-group">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="userEmail" class="col-form-label">E-Mail:</label>
                <input type="text" class="form-control" id="userEmail">
            </div>
            <div class="form-group">
                <label for="OldPassword" class="col-form-label">Prosim vlozte stary password:</label>
                <input type="password" class="form-control" id="oldPsswd">
            </div>
            <div class="form-group">
                <label for="NewPass1" class="col-form-label">Prosim vlozte novy password:</label>
                <input type="password" class="form-control" id="newPass1">
            </div>
            <div class="form-group">
                <label for="NewPass2" class="col-form-label">Prosim potvrdte password:</label>
                <input type="password" class="form-control" id="newPass2">
            </div>
            <input type="hidden" id="editUsersRowID" value="0">
        </form>
        <input  type="button" id="manageBtnUser" onclick="addUser('addNewUser')" value="Ulozit" class="btn btn-success">
    </div>

    </div>  <!-- End of container div -->



<?php require('View/Template/footer.phtml') ?>