<?php require('View/Template/header.phtml') ?>


<div class="container" style="margin-top: 100px; ">


<div class="justify-content-center">


    <div class="col-md-6 col-md-offset-3">


        <form method="post" action="register.php">
            <label>Vas Email: </label><br>
            <input class="form-control" name="email" type="email" placeholder="Vložte svou e-mailovou adresu"><br>
            <label>Vas password: </label><br>
            <input class="form-control" name="password" type="password" placeholder="Zadejte heslo"><br>
            <label>Potrdit password: </label><br>
            <input class="form-control" name="cPassword" type="password" placeholder="Potvrzení hesla"><br>
            <label>Vase telefonni cislo: </label><br>
            <input class="form-control" name="phone" placeholder="Vložte své telefonní číslo"><br>
            <label>Meno vasi firmy: </label><br>
            <input class="form-control" name="companyName" placeholder="Vložte název společnosti"><br>
            <label>Vase ICO: </label><br>
            <input class="form-control" name="ico" placeholder="Vložte svou e-mailovou adresu"><br>
            <label>Vase DIC: </label><br>
            <input class="form-control" name="dic" placeholder="Vložte svou e-mailovou adresu"><br>
            <label>Vase addressa: </label><br>
            <input class="form-control" name="address" placeholder="Vložte svou e-mailovou adresu"><br>
            <label>Mesto: </label><br>
            <input class="form-control" name="city" placeholder="Vložte svou e-mailovou adresu"><br>
            <label>Vase PSČ: </label><br>
            <input class="form-control" name="postCode" placeholder="Vložte svou e-mailovou adresu"><br>
            <input class="btn-primary" type="submit" name="submit" value="Register">


        </form>



    </div>


</div>


</div>



<?php require('View/Template/footer.phtml') ?>